version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
