version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Tokyo"
