# -*- encoding: utf-8 -*-

=begin
#国税庁API

#国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのクライアントAPI(https://www.invoice-kohyo.nta.go.jp/web-api/index.html)

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "kendama/version"

Gem::Specification.new do |s|
  s.name        = "kendama"
  s.version     = Kendama::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["uichi"]
  s.email       = ["37263474+uichi@users.noreply.github.com"]
  s.homepage    = "https://rubygems.org/gems/kendama"
  s.summary     = "適格請求書発行事業者公表システムWeb-APIのラッパー"
  s.description = "国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのRuby向けラッパーです。"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"

  # s.metadata["allowed_push_host"] = "TODO: Set to your gem server 'https://example.com'"

  s.metadata["homepage_uri"] = s.homepage
  s.metadata["source_code_uri"] = "https://github.com/uichi/kendama"
  s.metadata["changelog_uri"] = "https://github.com/uichi/kendama/blob/main/CHANGELOG.md"

  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
