# -*- encoding: utf-8 -*-

=begin
#国税庁API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "kendama/version"

Gem::Specification.new do |s|
  s.name        = "kendama"
  s.version     = Kendama::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["uichi"]
  s.email       = ["37263474+uichi@users.noreply.github.com"]
  s.homepage    = "https://rubygems.org/gems/kendama"
  s.summary     = "適格請求書発行事業者公表システムWeb-APIのラッパー"
  s.description = "国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのRuby向けラッパーです。"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"

  # s.metadata["allowed_push_host"] = "TODO: Set to your gem server 'https://example.com'"

  s.metadata["homepage_uri"] = s.homepage
  s.metadata["source_code_uri"] = "https://github.com/uichi/kendama"
  s.metadata["changelog_uri"] = "https://github.com/uichi/kendama/blob/develop/CHANGELOG.md"

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"

  # For more information and examples about making a new gem, check out our
  # guide at: https://bundler.io/guides/creating_gem.html

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'


  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  s.files = Dir.chdir(__dir__) do
    `git ls-files -z`.split("\x0").reject do |f|
      (File.expand_path(f) == __FILE__) || f.start_with?(*%w[bin/ test/ spec/ features/ .git .circleci appveyor])
    end
  end
  # s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.bindir = "exe"
  s.executables = s.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  # s.executables   = []
  s.require_paths = ["lib"]
end
