=begin
#国税庁API

#国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのクライアントAPI(https://www.invoice-kohyo.nta.go.jp/web-api/index.html)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kendama::V1Api
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'V1Api' do
  before do
    # run before each test
    @api_instance = Kendama::V1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1Api' do
    it 'should create an instance of V1Api' do
      expect(@api_instance).to be_instance_of(Kendama::V1Api)
    end
  end

  # unit tests for get_announcement_by_diff
  # 取得期間を指定して情報を取得
  # 取得期間を指定し、当該期間内に「更新年月日」が含まれる公表情報を取得
  # @param id 
  # @param from 
  # @param to 
  # @param type 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :division 
  # @option opts [String] :divide 
  # @return [ResponseBody]
  describe 'get_announcement_by_diff test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_announcement_by_number
  # 登録番号を指定して情報を取得
  # 指定された登録番号に係る登録年月日、取消年月日及び失効年月日に紐づく最新情報（履歴情報は任意）を取得
  # @param id 
  # @param number 
  # @param type 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :history 
  # @return [ResponseBody]
  describe 'get_announcement_by_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_announcement_by_valid
  # 登録番号と日付を指定して情報を取得
  # 登録番号及び指定された日付を基準日とした直近の登録年月日、取消年月日、失効年月日に紐づく情報を取得
  # @param id 
  # @param number 
  # @param day 
  # @param type 
  # @param [Hash] opts the optional parameters
  # @return [ResponseBody]
  describe 'get_announcement_by_valid test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
