=begin
#国税庁API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kendama::V1Api
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'V1Api' do
  before do
    # run before each test
    @api_instance = Kendama::V1Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1Api' do
    it 'should create an instance of V1Api' do
      expect(@api_instance).to be_instance_of(Kendama::V1Api)
    end
  end

  # unit tests for get_announcement_by_number
  # 登録番号を指定して情報を取得
  # 指定された登録番号に係る登録年月日、取消年月日及び失効年月日に紐づく最新情報（履歴情報は任意）を取得
  # @param id 
  # @param number 
  # @param type 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :history 
  # @return [ResponseBody]
  describe 'get_announcement_by_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
