=begin
#国税庁API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

# Common files
require 'kendama/api_client'
require 'kendama/api_error'
require 'kendama/version'
require 'kendama/configuration'

# Models
require 'kendama/models/announcement'
require 'kendama/models/response_body'

# APIs
require 'kendama/api/v1_api'

module Kendama
  class << self
    # Customize default settings for the SDK using block.
    #   Kendama.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
