openapi: 3.0.3
info:
  title: 国税庁API
  description: 国税庁が提供するインボイス制度適格請求書発行事業者公表システムWeb-APIを使用するためのクライアントAPI(https://www.invoice-kohyo.nta.go.jp/web-api/index.html)
  version: 1.0.0
paths:
  "/1/diff":
    get:
      operationId: getAnnouncementByDiff
      summary: 取得期間を指定して情報を取得
      description: 取得期間を指定し、当該期間内に「更新年月日」が含まれる公表情報を取得
      tags:
        - v1
      parameters:
        - $ref: "#/components/parameters/Id"
        - $ref: "#/components/parameters/From"
        - $ref: "#/components/parameters/To"
        - $ref: "#/components/parameters/Type"
        - $ref: "#/components/parameters/Division"
        - $ref: "#/components/parameters/Divide"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "./announcement.yaml#/components/schemas/ResponseBody"

components:
  parameters:
    Id:
      in: query
      name: id
      required: true
      schema:
        type: string
        description: アプリケーションID
    From:
      in: query
      name: from
      required: true
      schema:
        type: string
        description: 取得期間開始日
        example: "2024-10-01"
        format: date
    To:
      in: query
      name: to
      required: true
      schema:
        type: string
        description: 取得期間終了日
        example: "2024-10-01"
        format: date
    Type:
      in: query
      name: type
      required: true
      schema:
        type: string
        description: 応答形式
        example: 21
        enum:
          # - 01
          # - 11
          - 21
        default: 21
    Division:
      in: query
      name: division
      schema:
        type: string
        description: 人格区分
        default: 1
        enum:
          - 1
          - 2
    Divide:
      in: query
      name: divide
      schema:
        type: string
        description: 分割番号
        default: 1
        minLength: 1
        maxLength: 999999
